name: SpaceCommand
options:
  bundleIdPrefix: com.ZimengXiong
  deploymentTarget:
    macOS: "14.0"

targets:
  SpaceCommand:
    type: application
    platform: macOS
    sources: [Sources, Resources]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Resources/Info.plist
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 Zimeng Xiong"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        CODE_SIGN_ENTITLEMENTS: Resources/SpaceCommand.entitlements
        CODE_SIGN_IDENTITY: "-"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Bridging-Header.h
        OTHER_LDFLAGS: ["-framework", "Carbon", "-framework", "CoreGraphics"]
        PRODUCT_BUNDLE_IDENTIFIER: com.ZimengXiong.SpaceCommand
        MACOSX_DEPLOYMENT_TARGET: "14.0"
