name: SpaceCommand
options:
  bundleIdPrefix: com.SpaceCommand
  deploymentTarget:
    macOS: "14.0"

targets:
  SpaceCommand:
    type: application
    platform: macOS
    sources: [Sources]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 SpaceCommand"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        CODE_SIGN_ENTITLEMENTS: Resources/SpaceCommand.entitlements
        CODE_SIGN_IDENTITY: "-"
        # Bridging header for native macOS Private APIs
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Bridging-Header.h
        # Link frameworks: Carbon for hotkeys, CoreGraphics for private space APIs
        OTHER_LDFLAGS: ["-framework", "Carbon", "-framework", "CoreGraphics"]
        PRODUCT_BUNDLE_IDENTIFIER: com.SpaceCommand.SpaceCommand
        MACOSX_DEPLOYMENT_TARGET: "14.0"
